import { ReactNode } from "react";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="mx-[20%]">
        <div
          className="pl-[5%] flex flex-col items-center justify-center 
           bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200  
            md:flex-row md:items-start md:justify-between rounded-sm"
        >
          {children}
        </div>
      </body>
    </html>
  );
}
